apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec: 
  volumeName: jenkins-pv
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
